//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminMutfakYorum
    {
        public int ObjectId { get; set; }
        public int KisiId { get; set; }
        public System.DateTime Tarih { get; set; }
        [Required,MaxLength(250)]
        public string AdminYorumu { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Kullanıcılar Kullanıcılar { get; set; }
    }
}
