//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alisveris
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alisveris()
        {
            this.UrunAlis = new HashSet<UrunAlis>();
        }
    
        public int ObjectId { get; set; }
        public string MarketAdi { get; set; }
        public Nullable<System.DateTime> AlisverisTarihi { get; set; }
        public Nullable<int> FisTutari { get; set; }
        public string FisPath { get; set; }
        public string FisVisibleName { get; set; }
        public string FisName { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunAlis> UrunAlis { get; set; }
    }
}
