//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanıcılar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanıcılar()
        {
            this.AdminMutfakYorum = new HashSet<AdminMutfakYorum>();
            this.Borclandirma = new HashSet<Borclandirma>();
            this.Duyuru = new HashSet<Duyuru>();
            this.KullaniciYorum = new HashSet<KullaniciYorum>();
        }
    
        public int ObjectId { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }
        [Required(ErrorMessage ="Bu alan boş bırakılamaz.")]
        public string KullanıcıAdı { get; set; }
        [Required(ErrorMessage = "Bu alan boş bırakılamaz."), DataType(DataType.Password)]
        public string Parola { get; set; }
        public int GrupId { get; set; }
        public Nullable<int> GuncelBorc { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminMutfakYorum> AdminMutfakYorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borclandirma> Borclandirma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Duyuru> Duyuru { get; set; }
        public virtual Grup Grup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciYorum> KullaniciYorum { get; set; }
    }
}
