//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunAlis
    {
        public int ObjectId { get; set; }
        public int UrunId { get; set; }
        public int AlisId { get; set; }
        public Nullable<int> AlisMiktari { get; set; }
        public Nullable<int> BirimFiyat { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Alisveris Alisveris { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
