//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urun()
        {
            this.DuyuruBilgi = new HashSet<DuyuruBilgi>();
            this.Kullanim = new HashSet<Kullanim>();
            this.UrunAlis = new HashSet<UrunAlis>();
        }
    
        public int ObjectId { get; set; }
        public int DolapId { get; set; }
        public string UrunAdi { get; set; }
        public byte[] Fotograf { get; set; }
        public Nullable<int> StokMiktari { get; set; }
        public Nullable<int> Guncelleme { get; set; }
        public Nullable<int> UrunTipId { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Dolap Dolap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuyuruBilgi> DuyuruBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanim> Kullanim { get; set; }
        public virtual UrunTipi UrunTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunAlis> UrunAlis { get; set; }
    }
}
