//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_GenelGorunum
    {
        public string UrunAdi { get; set; }
        public byte[] Fotograf { get; set; }
        public Nullable<int> StokMiktari { get; set; }
        public string DolapAdi { get; set; }
        public Nullable<int> ToplamKullanim { get; set; }
        public Nullable<int> BirimFiyat { get; set; }
        public byte[] FisFoto { get; set; }
        public bool Deleted { get; set; }
    }
}
